### ISSUE TITLE
Other method to boot in HYP mode

### ISSUE THREAD

**Issue by TimJDFletcher** [vsiles/u-boot#1]
Hi, I read your thread about starting the Pi2 in HYP mode with u-boot and I have made it work with a different method:

I used this initial boot strap and normal u-boot to boot my Pi2 with all 4 cores working and HYP enabled.

cat bootblk.hyp u-boot.bin > /media/tim/firmware/u-boot.bin 

root@jessie-rpi:~# dmesg | grep HYP
[    0.322957] CPU: All CPU(s) started in HYP mode.
root@jessie-rpi:~# lscpu 
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv7 Processor rev 5 (v7l)
CPU max MHz:           800.0000
CPU min MHz:           800.0000

https://github.com/slp/rpi2-hyp-boot

**Comment by TimJDFletcher** [comment]
Note I didn't write any of the code I've just glued together various bits

**Comment by vsiles** [comment]
Oh clever, I understand what you did ! This is nice, no need to patch u-boot at all.
I've been in contact with u-boot's rpi branch maintainer, and at some point he wants to patch to allow boot in Hyp or Sec mode. 

Thanks for the feedback !

**Comment by TimJDFletcher** [comment]
Ideally we want u-boot to be able to handle a secure mode boot, but this was a fix for my problem of HYP mode on the Pi2. I'm writing up my notes now and I'll sent a link to the u-boot list.

**Comment by TimJDFletcher** [comment]
Notes written up: https://blog.night-shade.org.uk/2015/05/booting-a-raspberry-pi2-with-u-boot-and-hyp-enabled/

**Comment by vsiles** [comment]
thanks for the heads up

**Comment by vsiles** [comment]
I'm curious how the resulting binary is still working: by having ``kernel_old=1`` and linking your ``bootblk.bin`` at ``0x00000000``, the Pi bootloader will run your code, but then it will jump at ``0x8000``.  How does ``cat``ing your ``.bin`` with ``u-boot.bin`` put something relevant at ``0x8000`` ? (I'm not *that* familiar with binary executables).

**Comment by TimJDFletcher** [comment]
I am just using cat to glue the files together. The hyp mode bootblk starts at 0x0000, does its CPU setup and then jumps to 32k up the binary where u-boot is. The hyp block is padded to 32k for this reason.

**Comment by vsiles** [comment]
Oh I missed the padding in the Makefile. Thank you for the explanation !

**Comment by vsiles** [comment]
I just tried this way to boot in secure mode and it works fine.
Thank you very much for the idea !

V.
